version: '3.8'

services:
  nginx:
    container_name: '${PROJECT_NAME}-nginx'
    build:
      context: ./nginx
    volumes:
      #mount the project files from build folder
      - ./../build/:/var/www
      #mount log files
      - ./logs:/var/log
      #mount nginx conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm

  php-fpm:
    container_name: '${PROJECT_NAME}-php'
    build:
      context: ./php-fpm
    volumes:
      #mount the project files from build folder
      - ./../build/:/var/www